image: python:3

stages:
  - unit_test
  - integration_test

run_unit_tests:
  stage: unit_test
  only:
    - master
    - develop
    - merge_requests
  script:
    - python3 -m unittest discover .

run_integration_tests:
  stage: integration_test
  only:
    - master
    - develop
    - merge_requests
  script:
    - uname -a
    # - make test
