image: python:3

before_script:
  - sudo apt-get install git python-dev python-numpy python-opengl
  - sudo apt-get libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev
  - sudo apt-get libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
  - sudo apt-get libtiff5-dev libx11-6 libx11-dev fluid-soundfont-gm timgm6mb-soundfont
  - sudo apt-get xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic fontconfig fonts-freefont-ttf libfreetype6-dev
  - pip install pygame

stages:
  - unit_test
  - integration_test

run_unit_tests:
  stage: unit_test
  only:
    - master
    - develop
    - merge_requests
  script:
    - make unit

run_integration_tests:
  stage: integration_test
  only:
    - master
    - develop
    - merge_requests
  script:
    - uname -a
    # - make test
